version: '3'

services:
  mcp-server:
    build: .
    container_name: woo-mcp-server
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs 